import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
// import HeroSection from "@/components/HeroSection";

import HeroSection from "@/components/HeroSection2";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full relative flex flex-col items-start justify-start leading-[normal] tracking-[normal]">
        
          <Navbar/>
          <HeroSection/>
          {children}
        </div>
      </body>
    </html>
  );
}
